version: "3"

tasks:
  docs:build:
    desc: Render d2 diagram and assemble docs/
    cmds:
      - mkdir -p docs
      - d2 dashboard.d2 docs/dashboard.svg
      - |
        sed '/<!-- SVG_PLACEHOLDER -->/{
          r docs/dashboard.svg
          d
        }' index.html > docs/index.html
      - task-plus md2html --file README.md --dst docs --project dashboard --label Docs
    sources:
      - dashboard.d2
      - index.html
      - README.md
    generates:
      - docs/dashboard.svg
      - docs/index.html
      - docs/README.html

  clean:
    desc: Remove generated files
    cmds:
      - rm -rf docs

  check:
    desc: Check prior to deployment
    cmds:
      - task docs:build
